### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [clearent/nexus#2]
Hi,

I also build a nexus container using alpine 3.4. It run's fine.

Your setup also looks very nice.

Now I am trying to update to alpine linux 3.5. But now there seems to be an ssl issue.
Do You have experience with alpine 3.5 and nexus ??

Regards,

Hans Nieuwenhuis

**Comment by cavemandaveman** [comment]
For 3.5, Alpine decided to [switch](https://www.alpinelinux.org/posts/Alpine-3.5.0-released.html) to a LibreSSL implementation instead of OpenSSL. Of course, this breaks anything using OpenSSL, like this image.

It seems LibreSSL has some cipher issues ([relevant](https://news.ycombinator.com/item?id=12691733)), so I am holding off updating this image to 3.5 until those are ironed out.

What is the ssl error you are getting? If you want, you can try switching your dependencies to LibreSSL, but I have not had any luck so far.

**Comment by jhmnieuwenhuis** [comment]
Hi,

Thanks for the quick reponse.
I created an issue on the alpine site :
https://bugs.alpinelinux.org/issues/6680


Regards,

Hans Nieuwenhuis.

Met Vriendelijke Groet,

Hans Nieuwenhuis
Mobiel : 06-53476697

**Comment by cavemandaveman** [comment]
Great, I'll keep an eye on that bug report. For now, I am going to close this, as there is no issue with the current image as is.
